# Generated by Django 6.0.3 on 2026-03-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_pricingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='member_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='member_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
